config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  resources :users, only: [:show, :edit]
  resources :friendships, only: [:index, :create]
  patch 'friendships', to: 'friendships#update', as: 'accept_friend'
  delete 'friendships', to: 'friendships#destroy', as: 'delete_friend'
  resources :friendships, only: :show do
    resources :messages, only: :create
  end
  post "/sessions", to: "sessions#create"
  get "/sessions/queue", to: "sessions#queue"
  get "/sessions/:id", to: "sessions#show", as: "sessions_show"
  delete "/sessions", to: "sessions#destroy", as: "sessions_destroy"
  delete "/sessions/destroy_sessions", to: "sessions#destroy_sessions"
  get "/sessions/:session_id/reviews/new", to: "reviews#new", as: "review_new"
  post "/sessions/:session_id/reviews", to: "reviews#create", as: "new_review"
  patch '/user_languages/update', to: "user_languages#update_language", as: "update_language"
  get "/user_languages/new", to: "user_languages#new_language", as: 'new_language'
  post "/user_languages/setup", to: "user_languages#setup_language"
  post "/user_languages", to: "user_languages#create_language", as: 'add_user_language'
  delete '/user_languages/:id', to: 'user_languages#destroy_language', as: 'delete_language'
  get '/user_languages/edit', to: 'user_languages#edit_language', as: 'edit_language'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  has_many :messages
  belongs_to :participant_one, class_name: 'User', foreign_key: 'participant_one_id', required: true
  belongs_to :participant_two, class_name: 'User', foreign_key: 'participant_two_id', required: true
  validates :status, presence: true, inclusion: { in: ["pending", "accepted", "rejected"] }
  validate :not_yet_friends, on: :create

  def buddy(current_user)
    participant_one == current_user ? participant_two : participant_one
  end

  private

  def not_yet_friends
    errors.add(:participant_one, "is already a friend!") if participant_one.is_friend?(participant_two)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = current_user.friendships
    @friendships_and_buddies = @friendships.map do |friendship|
      if friendship.participant_one == current_user
        buddy = friendship.participant_two
      else
        buddy = friendship.participant_one
      end
      {
        friendship: friendship,
        buddy: buddy
      }
    end
    @messages = Message.all
    @friends_navbar_active = "d-flex flex-column justify-content-center align-items-center p-2 custom-navbar-border-bottom"
  end

  def show
    @friendship = Friendship.find(params[:id])
    @message = Message.new
  end


  def create
    @friend_id = params[:friend_id]
    @friendship = Friendship.new(status: "pending", participant_one_id: current_user.id, participant_two_id: @friend_id)
    @friendship.save
    #ajax here to update button
  end

  # def show - to display all of messages between you and your friends (through friendships#show)
  # end

  def update
    @friend_id = params[:friend_id] #participant one
    @friendship = Friendship.where(participant_one_id: @friend_id, participant_two_id: current_user.id)[0]
    @friendship.update(status: 'accepted', participant_one_id: @friend_id, participant_two_id: current_user.id)
    redirect_to user_path(@friend_id)
  end

  def destroy # decline or remove
    @friend_id = params[:friend_id]
    @friendship1 = Friendship.where(participant_one_id: @friend_id, participant_two_id: current_user.id).first
    @friendship2 = Friendship.where(participant_one_id: current_user.id, participant_two_id: @friend_id).first
    @friendship1.nil? ? @friendship2.destroy : @friendship1.destroy
    redirect_to friendships_path
  end

  private

  def friendship_params
    params.require(:friendship).permit(:participant_one_id, :participant_two_id, :status)
  end
end

app/views/friendships/_accept_reject.html.erb
<% case status %>
  <% when 'pending' %>
  <!-- is current user participant 1? i.e. sender of request - cancel-->
    <% if current_user.sent_request?(user) %>
      <%= form_tag("/friendships", method: 'delete') do%>
        <%= hidden_field_tag 'friend_id', user.id %>
        <%= submit_tag("Cancel Friend Request", class: "btn-orange-small") %>
      <% end %>
      <!-- is user participant 1? reject or accept (two buttons)-->
      <% else %>
            <!-- accept button -->
      <div class="acc-rej-btn-div">
      <%= form_tag("/friendships", method: 'patch') do%>
        <%= hidden_field_tag 'friend_id', user.id %>
        <%= submit_tag("Accept Friend Request", class: "btn-orange-small") %>
      <% end %>
            <!-- reject button -->
      <%= form_tag("/friendships", method: 'delete') do%>
        <%= hidden_field_tag 'friend_id', user.id %>
        <%= submit_tag("Decline Friend Request", class: "btn-orange-small") %>
        <% end %>
      <% end %>

      <% when 'accepted' %>
        <% if user.highly_rated? %>
          <div class="review-form-container">
            <p class="m-0">Highly rated! (insert badge icon)</p>
          </div>
        <% end %>
        <div class="review-form-container my-2">
          <h4 class="m-0"><%= user.first_name.capitalize %>'s Languages:</h4>
          <% user.languages.each do |language| %>
            <p class="m-0"><%= language.name.capitalize %></p>
          <% end %>
        </div>
        <!-- remove friend button -->
        <%= form_tag("/friendships", method: 'delete') do%>
          <%= hidden_field_tag 'friend_id', user.id %>
          <%= submit_tag("Remove Friend", class: "btn-orange-small") %>
        <% end %>
      </div>
      <% end %>
    <!--If they are not friends already-->

app/views/friendships/_message_preview.html.erb
<p data-controller="last-message" data-last-message-friendship-id-value="<%= friendship.id %>">
  <em><%= link_to message, friendship_path(friendship.id)%></em>
<p>

app/views/friendships/index.html.erb
<div class="w-100 h-100 d-flex flex-column align-items-center justify-content-start animate__animated animate__backInRight animation-content animate__faster">
  <div class="chat-header">
    <p class="p-0 my-2 mx-2"><%= link_to "< ", root_path , style: "text-decoration: none;" %></p>
    <p class="p-0 m-0 text-white"> Chats </p>
  </div>
  <% if @friendships_and_buddies.blank? %>
    <div class="messages-container">
      <h4 class="my-5 text-center">No connections yet.</h4>
    </div>
  <% else %>
    <div class="messages-container">
      <% @friendships_and_buddies.each do |friend| %>
        <div class="chat">
          <% @user = User.find(friend[:buddy].id) %>
          <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, crop: :fill, class: "avatar-large" %>
          <% else %>
            <%= image_tag "https://th.bing.com/th/id/OIP.ZT-Tw8tYy38htqch69vsGQAAAA?pid=ImgDet&rs=1", class: "avatar-large" %>
          <% end %>
          <div class="lastmsg">
            <%= link_to friend[:buddy].first_name + " " + friend[:buddy].last_name, user_path(@user) %>
            <% if friend[:friendship].status == "accepted" %>
              <% arr = [] %>
              <% @messages.each do |msg| %>
                <%  if msg.friendship_id  == friend[:friendship].id %>
                  <% arr.push(msg) %>
                <% end %>
              <% end %>
              <%# <%= link_to "open chat" , friendship_path(friend[:friendship].id)%>
              <div class="items">
                <% if arr.last.present? %>
                  <%= render 'message_preview', message: arr.last[:content], friendship: friend[:friendship]%>
                <% else %>
                  <%= render 'message_preview', message: "No messages", friendship: friend[:friendship]%>
                <%end %>
              </div>
            <% else %>
              <%= render 'accept_reject', status: friend[:friendship].status, user: friend[:buddy]%>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/friendships/show.html.erb
<div data-controller="friendship-subscription"
  data-friendship-subscription-friendship-id-value="<%= @friendship.id %>"
  data-friendship-subscription-current-user-id-value="<%= current_user.id %>"
>
  <div class="chat-header">
    <p class="p-0 m-0">
      <%= link_to "<", friendships_path, class: "p-0 my-2 mx-2" %>
      <% if @friendship.buddy(current_user).photo.attached? %>
        <%= cl_image_tag @friendship.buddy(current_user).photo.key, crop: :fill, class: "avatar-small" %>
      <% else %>
        <%= image_tag "https://th.bing.com/th/id/OIP.ZT-Tw8tYy38htqch69vsGQAAAA?pid=ImgDet&rs=1", class: "avatar-large" %>
      <% end %>
      <p class="mx-2 my-0 text-white"><%= @friendship.buddy(current_user).first_name%> <%= @friendship.buddy(current_user).last_name%></p>
    </p>
  </div>
  <div class="messages" data-friendship-subscription-target="messages">
    <% @friendship.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render "messages/chat_form", friendship: @friendship, message: @message %>
</div>