config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  resources :users, only: [:show, :edit]
  resources :friendships, only: [:index, :create]
  patch 'friendships', to: 'friendships#update', as: 'accept_friend'
  delete 'friendships', to: 'friendships#destroy', as: 'delete_friend'
  resources :friendships, only: :show do
    resources :messages, only: :create
  end
  post "/sessions", to: "sessions#create"
  get "/sessions/queue", to: "sessions#queue"
  get "/sessions/:id", to: "sessions#show", as: "sessions_show"
  delete "/sessions", to: "sessions#destroy", as: "sessions_destroy"
  delete "/sessions/destroy_sessions", to: "sessions#destroy_sessions"
  get "/sessions/:session_id/reviews/new", to: "reviews#new", as: "review_new"
  post "/sessions/:session_id/reviews", to: "reviews#create", as: "new_review"
  patch '/user_languages/update', to: "user_languages#update_language", as: "update_language"
  get "/user_languages/new", to: "user_languages#new_language", as: 'new_language'
  post "/user_languages/setup", to: "user_languages#setup_language"
  post "/user_languages", to: "user_languages#create_language", as: 'add_user_language'
  delete '/user_languages/:id', to: 'user_languages#destroy_language', as: 'delete_language'
  get '/user_languages/edit', to: 'user_languages#edit_language', as: 'edit_language'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :user_languages, dependent: :destroy
  has_many :languages, through: :user_languages
  has_many :reviews
  has_many :messages
  has_many :friendships_created, class_name: "Friendship", foreign_key: :participant_one, dependent: :destroy
  has_many :friendships_received, class_name: "Friendship", foreign_key: :participant_two, dependent: :destroy
  has_many :sessions, foreign_key: :participant_one, dependent: :destroy
  has_many :inverse_sessions, class_name: "Session", foreign_key: :participant_two, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true, inclusion: { in: ["male", "female", "prefer not to say"] }
  validates :date_of_birth, presence: true
  validate :validate_age




  def friendships
    friendships_created + friendships_received
  end

  def is_friend?(user)
    condition1 = Friendship.where(participant_one: user, participant_two: self).exists?
    condition2 = Friendship.where(participant_one: self, participant_two: user).exists?
    condition1 || condition2
  end

  def friendship_status(friend)
    friendship1 = Friendship.where(participant_one: friend, participant_two: self)
    friendship2 = Friendship.where(participant_one: self, participant_two: friend)
    if friendship1.exists?
      friendship1[0].status
    else
      friendship2[0].status
    end
  end

  def sent_request?(receiver)
    # grab the instances of a friendship
    sent = Friendship.where(participant_one: self, participant_two: receiver)
    # is participant one sender? yes or no -- return boolean
    sent.exists?
  end

  def highly_rated?
    sessions = Session.where(participant_one: self).or(Session.where(participant_two: self))
    reviews = sessions.map { |session| session.reviews.where.not(user_id: self.id) }.flatten
    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    return ((sum.to_f / reviews.length) >= 4)
  end

  # def online?
  #   updated_at > 2.minutes.ago
  # end

  private

  def validate_age
    if date_of_birth.present? && date_of_birth > 18.years.ago.to_date
        errors.add(:date_of_birth, 'You should be over 18 years old.')
    end
  end
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
  validates :language_id, uniqueness: { scope: :user_id, message: "Already selected as your language" }
end

app/controllers/user_languages_controller.rb
class UserLanguagesController < ApplicationController
  #user_language selection page directly after sign up
  def new_language
    @user = current_user
  end

  #user_language creation action after initial sign up selection
  def setup_language
    @x_ids = params[:user_language][:user_languages].reject(&:blank?)
    @ids = @x_ids.map(&:to_i)
    if @ids.blank?
      @message = "You must select at least one language."
      @user = current_user
      render :new_language, status: :unprocessable_entity
    else
      @ids.each do |id|
        unless current_user.languages.map(&:id).include?(id)
          @language = Language.find(id)
          @user_language = UserLanguage.new(user_language_params)
          @user_language.user = current_user
          @user_language.language = @language
          @user_language.save
        end
      end
      redirect_to root_path
    end
  end

  #called when user updates languages in edit profile page
  def create_language
    @current_ids = current_user.languages.map(&:id)
    @x_ids = params[:user_language][:user_languages].reject(&:blank?)
    @ids = @x_ids.map(&:to_i)
    @delete_ids = (@current_ids - @ids)
    unless @delete_ids.blank? || @ids.blank?
      @delete_ids.each do |id|
        object = UserLanguage.where(language_id: id).where(user_id: current_user.id)[0]
        object.destroy
      end
    end
    if @ids.blank?
      redirect_to edit_user_registration_path
      flash[:alert] = "You must select at least one language"
    else
      @ids.each do |id|
        unless current_user.languages.map(&:id).include?(id)
          @language = Language.find(id)
          @user_language = UserLanguage.new(user_language_params)
          @user_language.user = current_user
          @user_language.language = @language
          @user_language.save
        end
      end
      redirect_to edit_user_registration_path
      flash[:notice] = "Successfully saved languages"
    end
  end

  def edit_language
    @user_languages = current_user.user_languages
  end

  def update_language #update
    @user_languages = current_user.user_languages
    id_array = params[:user_language_ids].map(&:to_i)
    @user_languages.each do |user_language|
      if id_array.include?(user_language.id)
        user_language.update(active: true)
      else
        user_language.update(active: false)
      end
    end
    # after update then we need to go to session create which then goes to sessions/queue
    language_ids = @user_languages.map { |user_language| user_language.language.id if user_language.active? }.reject { |x| x == nil }
    if Session.where(participant_two_id: nil).where(language_id: language_ids).where.not(participant_one_id: current_user.id).blank?
      language_ids.each do |id|
        session = Session.new(participant_one_id: current_user.id, language_id: id)
        session.save
      end
      redirect_to sessions_queue_path
    else
      @session = Session.where(participant_two_id: nil).where(language_id: language_ids).sample
      @session.participant_two = current_user
      if @session.save
        redirect_to sessions_show_path(@session)
      else
        # render some page with error
      end
    end
  end

  # come back to this depending on the users/edit page
  # def destroy_language
  #   @language = UserLanguage.find(params[:language_id])
  #   @language.destroy
  # end

  private

  def user_language_params
    params.require(:user_language).permit(:user_id, :active, :language_id)
  end

  def capitalize(array)
    @language_names = array.map do |language|
      language.name.capitalize
    end
    return @language_names
  end
end

app/views/user_languages/edit_language.html.erb
<div class="w-100 h-100 d-flex flex-column align-items-center justify-content-center animate__animated animate__backInRight animation-content animate__faster">
  <div class="d-flex flex-column align-items-center justify-content-around h-75 w-75">
    <h1 class="text-center pt-20">Choose your language:</h1>
    <div class="button-container">
      <div class="form" data-controller="session-language">
        <%= form_tag update_language_url, method: :patch do %>
          <% @user_languages.each do |user_language| %>
            <div class= "checkbox"><%= check_box_tag 'user_language_ids[]', user_language.id, false, data: { action: "click->session-language#disable", session_language_target: 'checkbox'} %>
              <p><%= user_language.language.name.capitalize %></p>
            </div>
          <% end %>
            <div class="lounge-button">
              <%= submit_tag 'Take me to Lounge!', class: "btn-orange", disabled: true, data: { session_language_target: 'button' }%>
          <% end %>
            </div>
      </div>
    </div>
      <%= link_to "Back to Home", root_path, class: "btn-orange" %>
  </div>
</div>

app/views/user_languages/new_language.html.erb
<div class="w-100 h-100 d-flex flex-column align-items-center justify-content-start animate__animated animate__backInRight animation-content animate__faster">
  <div class="d-flex flex-column align-items-center justify-content-around h-75 w-75">
    <h2 class="text-center">Select your languages</h2>
    <div class="review-form-container">
      <%= simple_form_for :user_language, method: :post, html: { class: "w-100 p-1" }, url: user_languages_setup_path do |f| %>
        <%= f.label :user_languages, 'My Languages*' %>
        <%= f.input :user_languages,
                    required: true,
                    label: false,
                    collection: Language.all,
                    input_html: {multiple: true, include_blank: false, data: {controller: "tom-select", tom_select_options_value: {tags: true, items: @user.languages.map(&:id)}}} %>
        <% if @message %>
          <p class="text-danger"><%= @message %></p>
        <% end %>
        <%= f.submit "Save Changes", class: "btn-orange" %>
      <% end %>
    </div>
  </div>
</div>