config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  resources :users, only: [:show, :edit]
  resources :friendships, only: [:index, :create]
  patch 'friendships', to: 'friendships#update', as: 'accept_friend'
  delete 'friendships', to: 'friendships#destroy', as: 'delete_friend'
  resources :friendships, only: :show do
    resources :messages, only: :create
  end
  post "/sessions", to: "sessions#create"
  get "/sessions/queue", to: "sessions#queue"
  get "/sessions/:id", to: "sessions#show", as: "sessions_show"
  delete "/sessions", to: "sessions#destroy", as: "sessions_destroy"
  delete "/sessions/destroy_sessions", to: "sessions#destroy_sessions"
  get "/sessions/:session_id/reviews/new", to: "reviews#new", as: "review_new"
  post "/sessions/:session_id/reviews", to: "reviews#create", as: "new_review"
  patch '/user_languages/update', to: "user_languages#update_language", as: "update_language"
  get "/user_languages/new", to: "user_languages#new_language", as: 'new_language'
  post "/user_languages/setup", to: "user_languages#setup_language"
  post "/user_languages", to: "user_languages#create_language", as: 'add_user_language'
  delete '/user_languages/:id', to: 'user_languages#destroy_language', as: 'delete_language'
  get '/user_languages/edit', to: 'user_languages#edit_language', as: 'edit_language'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_session, only: %i[new create]

  def new
    @review = Review.new
    if @session.participant_one_id == current_user.id
      @user = @session.participant_two
    else
      @user = @session.participant_one
    end
  end

  def create
    @review = Review.new(review_params)
    @review.session = @session
    @review.user_id = current_user.id
    if @review.save
      # AJAX HERE to change button
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :user_id, :session_id)
  end

  def set_session
    @session = Session.find(params[:session_id])
  end
end

app/views/reviews/_review_buttons.html.erb
<%= simple_form_for [session, review], url: new_review_path(session),
  html: {
    data: {controller:"review-buttons", action: "turbo:submit-end->review-buttons#changeTextRate"},
    class: "w-100 d-flex flex-column align-items-center justify-content-center"
    } do |f| %>
    <%= f.input :rating, label: false, collection: (1..5).to_a, input_html: {data: {controller: "star-rating", options: {tooltip: false}}} %>
    <%= f.submit "Submit review", class: "btn-orange" %>
    <%# , data: { controller:"review-buttons", action: "click->review-buttons#changeTextRate" } %>
  <% end %>
  <% unless current_user.is_friend?(user) %> <!-- send friend req-->
    <%= form_tag("/friendships", method: 'post', class: "w-100") do%>
    <%= hidden_field_tag 'friend_id', user.id %>
    <%= submit_tag("Send Friend Request", class: "btn-orange", data: { controller:"review-buttons", action: "click->review-buttons#changeTextRequest" }) %>
  <% end %>
<% end %>

app/views/reviews/new.html.erb
<div class="w-100 h-100 d-flex flex-column align-items-center justify-content-center animate__animated animate__backInRight animation-content animate__faster">
  <div class="d-flex flex-column align-items-center justify-content-around h-75 w-75">
    <div class="d-flex flex-column align-items-center justify-content-center my-4 w-100">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, crop: :fill, class: "avatar-flex" %>
      <% else %>
        <%= image_tag "https://th.bing.com/th/id/OIP.ZT-Tw8tYy38htqch69vsGQAAAA?pid=ImgDet&rs=1", class: "avatar-flex" %>
      <% end %>
      <div class="my-2">
        <h2 class="text-center"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h2>
      </div>
    </div>
    <div class="review-form-container" data-controller="review-buttons">
      <h4 class="text-center">Rate your experience</h4>
      <%= render "review_buttons", session: @session, review: @review, user: @user %>
    <%= link_to "Continue", root_path, class: "btn-orange" %>
  </div>
</div>

<!-- Review form
<div class="container">
  <div class="rating-card">
    <h2>Rate your experience!</h2>
    <% unless current_user.is_friend?(@user) %>
      <%= form_tag("/friendships", method: 'post') do%>
        <%= hidden_field_tag 'friend_id', @user.id %>
        <%= submit_tag("Add Friend") %>
      <% end %>
    <% end %>
  </div>

  <div class="friend-request">
    <% if current_user.is_friend?(@user) %>
      <% status = current_user.friendship_status(@user) %>
       <% case status %>
         <% when 'pending' %>

          <% if current_user.sent_request?(@user) %>
            <%= form_tag("/friendships", method: 'delete') do%>
            <%= hidden_field_tag 'friend_id', @user.id %>
            <%= submit_tag("Cancel Friend Request") %>
            <% end %>

          <% else %>

            <%= form_tag("/friendships", method: 'patch') do%>
            <%= hidden_field_tag 'friend_id', @user.id %>
            <%= submit_tag("Accept Friend Request") %>
            <% end %>
          <% end %>
        <% when 'accepted' %>
          <p>You are already friends</p>
        <% end %>
    <% else %>
      <h4>Send Friend Request</h4>
        <%= form_tag("/friendships", method: 'post') do%>
        <%= hidden_field_tag 'friend_id', @user.id %>
        <%= submit_tag("Add Friend") %>
        <% end %>
    <% end %>
  </div>

  <div class="home-link">

    <%= link_to "Back to Lounge", root_path %>
  </div>
</div>
-->